### ISSUE TITLE
Availability of fec package and 2012 presidential cycle

### ISSUE THREAD

**Issue by schoend** [beanumber/fec#15]
After package installation as follows:
__
install.packages("devtools")
devtools::install_github("beanumber/fec")
library(fec)
data(fec)
__
I see the following in response to >data(package="fec")

Data sets in package ‘fec’:
fec_vars                     FEC variables
house_elections_2012         Congressional election results
__
I do not see the data related to Figures 2.1, 2.2 in the Baumer textbook which, in turn, is referenced in Exercise 5.10, 5.11.  This is just fyi.  Am I missing something?

**Comment by beanumber** [comment]
There is no data set called `fec` that is provided by the package. The data is far too large to package via this mechanism. The `fec` package provides sort of API to the FEC data. It follows the paradigm of the [`etl` package](https://github.com/beanumber/etl). 

I haven't had time to write a README for this package yet, but if you look at the `etl` documentation, the use of `fec` is the same. 

I'll make a note of streamlining this for the 2nd edition. Thanks!
